### PR TITLE
bump wagtail and django's versions to 2.0

### PR DESCRIPTION
**Pull request by mai0elkady**
upgrading django, wagtail and wagtailmenus for issue #82

### CODE REVIEW

**Comment by hnykda** [comment]
@mai0elkady Great job! It seems wagtail has official version 2.0. Could you please update the requirements.txt to remove that `rc1` from there? Otherwise, perfect.

**Comment by mai0elkady** [comment]
@hnykda Done! and it seems to be working well

**Comment by hnykda** [comment]
Awesome, thanks. I will merge it right after we merge redesign branch (hopefully soon).

**Comment by hnykda** [comment]
Will try to merge this this week.

**Comment by hnykda** [comment]
I merged that locally because I had to fix few conflicts. https://github.com/ea-czech-republic/efektivnialtruismus.cz/commit/62a21311210c9c0619c8ea5febce7275af82e2c3

**Pull request closed without merging**
