### PR TITLE
Centering pages

### PR DESCRIPTION
**Pull request by Daver2910**
Centered all pages (medium size screens only, not mobile) using bootstrap

### CODE REVIEW

**Comment by hnykda** [comment]
Looks good :+1: . 

What do you think about the layout of the menu now? Isn't it weird that it is "too wide" now?

image

Otherwise close to merge.

**Comment by Daver2910** [comment]
That is completely up to you guys. I have it set up now so that it is easily adjustable and more importantly responsive. 
Let me know if you want to adjust it and i will do so.

**Comment by hnykda** [comment]
This is where we need us to become more designers/UXers vs developers... What does your internal designer things? What does @brandnk thinks? 

I would probably prefer make it the same size as the rest of the inner content, basically following the current layout:

image

**Comment by Daver2910** [comment]
Personally, I would like the navbar wider than the content. 
Content in a jumbotron wrapper( in the center of the screen about 80% of the width)
Forms, and bullet-points centered and about 60% width.

Also, I would suggest some color :)

**Comment by hnykda** [comment]
Agree. Cool, so let's merge it now.

**Pull request merged**
